### ISSUE TITLE
BUG: User can skip privacy key generation by pressing browsers back button 

### ISSUE THREAD

**Issue by P3nny** [railslove/recover-backlog#41]
Setting up a profile on https://rcvr.app/ I wanted to document the process and pressed pressed browsers "back"-key kind of accidentally. 
That made the application jump directly to https://rcvr.app/business/dashboard. 
I have no idea how to get to my private key now.

**Comment by salimhb** [comment]
Nice catch!

I tested further to see what can be done in this state. I could add a company and and area. However, it's not possible to generate a QR code because it requires the public key. It fails with the error "Owner 1294 has no public_key".
So basically, there's no risk of data inconsistency. If I logout and login again, the on-boarding screen is shown again to generate a private key.
